def ai_ranking_prompt(query, batch_size, papers_json, current_batch, total_batches, total_papers):
    return (
        f"You are an expert research analyst processing batch {current_batch} of {total_batches} for the query: '{query}'\n"
        f"Total papers across all batches: {total_papers}. This batch contains {batch_size} papers.\n\n"
        f"CRITICAL INSTRUCTIONS:\n"
        f"- Analyze each paper's TITLE carefully to understand its specific focus\n"
        f"- Write a UNIQUE explanation for EACH paper based on its actual title content\n"
        f"- Explain HOW each paper's specific topic/method relates to '{query}'\n"
        f"- Be SPECIFIC about what each paper contributes (don't use generic phrases)\n"
        f"- Each explanation must be different - analyze the actual research focus from the title\n\n"
        f"For each paper, provide:\n"
        f"1. What specific aspect of '{query}' does this paper address (based on its title)?\n"
        f"2. What methodology, tool, or approach does it present?\n"
        f"3. Why would this be valuable for '{query}' research?\n\n"
        f"FORBIDDEN PHRASES: 'relevant to the query', 'provides insights', 'contributes to', 'addresses mentioned'\n"
        f"REQUIRED: Mention the paper's specific focus/method/tool from its title in your explanation\n\n"
        f"EXAMPLE (for query 'machine learning'):\n"
        f"Title: 'Deep Neural Networks for Image Classification'\n"
        f"Explanation: 'This paper develops deep neural network architectures specifically for image classification tasks, presenting convolutional layer optimizations and training algorithms that improve accuracy in visual recognition systems.'\n\n"
        f"Return a JSON array with ALL {batch_size} papers, each having:\n"
        "- title: exact title from input (use 't' field value)\n"
        "- authors: exact authors from input (use 'a' field value)\n"
        "- explanation: SPECIFIC 2-3 sentences analyzing this paper's unique contribution based on its title\n\n"
        f"Papers to analyze:\n{papers_json}\n\n"
        f"Return ONLY a JSON array with ALL {batch_size} papers:"
    )

def citation_ranking_prompt(query, batch_size, papers_json, current_batch, total_batches, total_papers):
    return (
        f"You are an expert research analyst processing batch {current_batch} of {total_batches} for the query: '{query}'\n"
        f"Total papers across all batches: {total_papers}. This batch contains {batch_size} papers.\n\n"
        f"CRITICAL INSTRUCTIONS:\n"
        f"- Analyze each paper's TITLE carefully to understand its specific research focus\n"
        f"- Consider both citation impact ('c' field) and title-based relevance to '{query}'\n"
        f"- Write a UNIQUE explanation for EACH paper based on its actual title and citation count\n"
        f"- Explain HOW each paper's specific methodology/tool relates to '{query}'\n"
        f"- Mention why its citation count indicates importance in the field\n\n"
        f"For each paper, provide:\n"
        f"1. What specific aspect/method of '{query}' does this paper focus on (from title)?\n"
        f"2. How do its citations (c field) reflect its impact in '{query}' research?\n"
        f"3. What makes this paper's approach unique or influential?\n\n"
        f"FORBIDDEN PHRASES: 'relevant to the query', 'provides insights', 'contributes to'\n"
        f"REQUIRED: Reference the paper's specific focus from its title AND its citation impact\n\n"
        f"EXAMPLE (for query 'testing'):\n"
        f"Title: 'Automated Unit Testing Framework' (10 citations)\n"
        f"Explanation: 'This paper introduces an automated unit testing framework with 10 citations, indicating solid adoption in software testing communities. The framework provides automated test case generation and execution, reducing manual testing overhead in software development.'\n\n"
        f"Return a JSON array with ALL {batch_size} papers, each having:\n"
        "- title: exact title from input (use 't' field value)\n"
        "- authors: exact authors from input (use 'a' field value)\n"
        "- citations: citation count from input (use 'c' field value)\n"
        "- explanation: SPECIFIC analysis of this paper's unique focus and citation impact\n\n"
        f"Papers to analyze:\n{papers_json}\n\n"
        f"Return ONLY a JSON array with ALL {batch_size} papers:"
    )
